 	      ##################################################
              #  __________________________________________    #
              # /\                                         \   #
              # \_| Make file for Advance Database         |   #
              #   |         	Extra Credit Assignment    |   #
              #   |   _____________________________________|_  #
              #    \_/_______________________________________/ #
              ##################################################			
btree_compare: 
	cc -g -o btree btree_compare.c

run:
	./btree
gdb:
	gdb ./btree
val:
	valgrind --leak-check=yes ./btree 
clean:
	rm btree  
